### ISSUE TITLE
cal_days_in_month shim signature is different than PHP which leads to type conversion issue and wrong results

### ISSUE THREAD

**Issue by fredericgboutin-yapla** [fisharebest/ext-calendar#14]
```php
 function cal_days_in_month($calendar_id, $month, $year)
```

VERSUS

```php
cal_days_in_month(int $calendar, int $month, int $year): int
```

Source: https://www.php.net/manual/en/function.cal-days-in-month.php

So when you call, for example:

```php
cal_days_in_month(CAL_GREGORIAN, '04', '2022');
```

It returns `28` even though it should return `30`.

**Comment by fisharebest** [comment]
Thanks for reporting this.

We cannot add type-hints as we must support PHP 5.3.

But we can cast the parameters to integers, which will fix the issue.

**Comment by fisharebest** [comment]
I have just tagged a `2.6.0` release, which is now available from packagist:

https://packagist.org/packages/fisharebest/ext-calendar
