### ISSUE TITLE
Method daysInMonth seems to be not working correctly

### ISSUE THREAD

**Issue by csof3cen** [fisharebest/ext-calendar#15]
$cal = new Fisharebest\ExtCalendar\FrenchCalendar();
>>> echo $cal->daysInMonth(2022, 8)
30⏎
>>> echo $cal->daysInMonth(2022, 9)
30⏎
>>> echo $cal->daysInMonth(2022, 10)
30⏎
>>> echo $cal->daysInMonth(2022, 11)
30⏎
>>> echo $cal->daysInMonth(2022, 12)
30⏎
>>> echo $cal->daysInMonth(2022, 1)
30⏎
>>> echo $cal->daysInMonth(2022, 2)
30⏎
>>> echo $cal->daysInMonth(2023, 2)
30⏎
>>> echo $cal->daysInMonth(2025, 3)
30⏎

For all given year and month, the method is always returning 30

**Comment by fisharebest** [comment]
This is correct.  In the French calendar, all months have 30 days!

There is a special 13th month "Jour Complementaires" which has either 5 or 6 days.

See https://en.wikipedia.org/wiki/French_Republican_calendar for more information

**Comment by csof3cen** [comment]
Ok, I see. But for the name given to this function i think it's a bad design, it don't make sense to create a function to always return the same number. I think it should be stored in something like a constant and then, this function returns the real number of days in a given month. Thank you !
